<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ReportDoanhThu.rdlc" />
    <None Remove="ReportGiaoDich.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ReportDoanhThu.rdlc" />
    <EmbeddedResource Include="ReportGiaoDich.rdlc">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="ReportViewerCore.WinForms.X" Version="16.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="dsDoanhThu.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsDoanhThu.xsd</DependentUpon>
    </Compile>
    <Compile Update="dsGiaoDich.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsGiaoDich.xsd</DependentUpon>
    </Compile>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="dsDoanhThu.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsDoanhThu.Designer.vb</LastGenOutput>
    </None>
    <None Update="dsGiaoDich.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsGiaoDich.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

</Project>